In [4]:
import numpy as np
import pytorch as torch
import random

ModuleNotFoundError: No module named 'pytorch'

In [11]:
class World:
  def __init__(self, n, num_tasks):
    # Initialize nxn map 
    self.n = n
    self.num_tasks = num_tasks
    
    # Generate blank map
    world_map = np.zeros(n*n)
    # Add tasks at front
    world_map[:num_tasks] = 1
    # Randomly shuffle the tasks in 
    np.random.shuffle(world_map)
    # Make map the right dimensions
    world_map = world_map.reshape((n, n))
    
    self.map = world_map
  def check_task_accomplished(self, location):
    pass
  def do_task(self, location):
    pass


In [12]:
a = World(5, 2)
print(a.map)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
class Agent:
  model = Model()
  
  def __init__(self, id, world, vision_radius=3):
    self.id = id
    self.world = world
    self.alive = True
    self.location = (0,0) #change later
    self.vision_radius = vision_radius

  def get_action():
    pass

  def update_location(move_action):
    # 0: up
    # 1: up + right
    # 2: right
    # 3: down + right
    # 4: down
    # 5: down + left
    # 6: left
    # 7: left + up
    # Move, but stay in bounds
    if move_action == 0 or move_action == 1 or move_action == 7:
        self.location[1] = max(0, self.location[1]-1) 
    if move_action >= 1 and move_action <= 3:
        self.location[0] = min(self.world.n-1, self.location[0]+1)
    if move_action >= 3 and move_action <= 5:
        self.location[1] = min(self.world.n-1, self.location[1]+1)
    if move_action >= 5 and move_action <= 7:
        self.location[0] = max(0, self.location[0]-1)
    return self.location
    

class Crewmate(Agent):
  def __init__(self, id, world, vision_radius=3):
    super().__init__(id, world, vision_radius)

class Impostor(Agent):
  def __init__(self, id, world, vision_radius=3, kill_distance=1):
    super().__init__(id, world, vision_radius)
    self.kill_distance = kill_distance

class Game:
  def __init__(self, map_size, num_tasks, num_agents, max_steps):
    self.n = map_size
    self.t = num_tasks
    self.num_agents = num_agents
    self.max_steps = max_steps
    #Arbitrary numbers
    self.kill_distance = 1
    self.agent_vision_radius = 3
    self.task_reward = 3
    self.reset()

  def reset(self):
    # Generate a new world
    self.world = World(self.n, self.t)
    # Make all but one crewmates
    self.impostor_index = random.randint(0, self.num_agents-1)
    self.agents = []
    for i in range(self.num_agents):
        if i == self.impostor_index:
            self.agents.append(Impostor(i, self.world, self.agent_vision_radius, self.kill_distance))
        else:
            self.agents.append(Crewmate(i, self.world, self.agent_vision_radius))
    # Whether the game is ongoing
    self.ongoing = True
    self.num_steps = 0
  
  def step(self):
    # This function returns the new observation for each agent,
    # The reward they got,
    # Whether the game is done 
    to_kill = None
    rewards = np.zeroes(num_agents)
    
    for agent in self.agents:
        # Dead agents cannot do anything
        if not agent.alive:
            continue 
        action = agent.get_action()
        # Assume action to be a row vector 
        # Index 0 represents kill(0) or move(1)
        # Index 1 represents which direction to move
        # Index 2 represents who to kill
        # Remainder of the k*(n-1) indices represent messages to each other agent
        if action[0] == 0:
            # Only the impostor can kill someone else 
            if agent.id != self.impostor_index:
                continue
            # We are killing this person, they die in the next round
            to_kill = action[2]
            can_kill = check_proximity(to_kill) #implement checking that the person is close enough to kill
            if can_kill:
                rewards[agent.]
            else:
                to_kill = None
        if action[0] == 1:
            # We are moving
            new_location = agent.update_location(action[1])
            task_done = self.world.check_task_accomplished(new_location)
            if task_done:
                rewards[agent.id] = self.task_reward    
    
    self.num_steps += 1
    if self.num_steps >= self.max_steps:
        self.ongoing = False
        
    pass

  def get_observation(self, agent):
    # Get a 2*vision_radius+1 size square representing what the agent can see
    pass

  def generate_agent_rewards(self, agent):
    # If the agent is an crewmate in the square and the task was just done,
    # award the agent for doing the task
    # If the agent is an impostor and they just killed someone, award the agent 
    # for killing them
    
    
    pass
  
  def generate_rewards(self):
    rewards = []
    for agent in self.agents:
        rewards.append(generate_agent_rewards(agent))
    return np.array(rewards)

  def transition(self, actions):
    # Transition the world state, where actions is 
    # an array of the actions of each agent 
    # Actions are move or kill 
    
    pass
    
  
  
class Model():
  pass

In [1]:
import sys

In [3]:
sys.path

['/data/rsg/nlp/juanmoo1/projects/04_amongus/among_us_project',
 '/data/rsg/nlp/juanmoo1/miniconda2/envs/amongus/lib/python37.zip',
 '/data/rsg/nlp/juanmoo1/miniconda2/envs/amongus/lib/python3.7',
 '/data/rsg/nlp/juanmoo1/miniconda2/envs/amongus/lib/python3.7/lib-dynload',
 '',
 '/data/rsg/nlp/juanmoo1/miniconda2/envs/amongus/lib/python3.7/site-packages',
 '/data/rsg/nlp/juanmoo1/miniconda2/envs/amongus/lib/python3.7/site-packages/IPython/extensions',
 '/data/rsg/nlp/juanmoo1/.ipython']