In [1]:
# Import Project
import sys
sys.path.append('.')
from amongus.agent import *
from amongus.game import *
from amongus.model import *
from amongus.world import *

# External Packages
import numpy as np
import torch

In [2]:
map_size = 10
num_tasks = 5
num_agents = 5
max_steps = 200

game = Game(map_size, num_tasks, num_agents, max_steps)

In [3]:
print(game.world)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
print(game)

------------------------------------------
|   |   |   |   | G |   |   |   |   |   |
------------------------------------------
|   |   |   |   |   |   |   |   |   | C |
------------------------------------------
|   |   |   |   |   |   |   |   |   |   |
------------------------------------------
|   |   |   | G |   |   |   |   |   |   |
------------------------------------------
|   | G |   |   |   |   |   |   | C |   |
------------------------------------------
|   |   |   |   |   |   |   | G |   |   |
------------------------------------------
|   |   |   |   |   | I |   |   |   |   |
------------------------------------------
| C |   |   |   |   |   |   |   |   |   |
------------------------------------------
|   |   |   |   |   |   |   |   |   | C |
------------------------------------------
|   |   |   |   |   |   |   |   |   |   |
------------------------------------------



In [6]:
game.agents

[ID: 0, Role: Impostor, Location: (8, 8),
 ID: 1, Role: Crewmate, Location: (6, 0),
 ID: 2, Role: Crewmate, Location: (2, 3),
 ID: 3, Role: Crewmate, Location: (7, 8),
 ID: 4, Role: Crewmate, Location: (7, 7)]