In [17]:
# Import Project
import sys
sys.path.append('.')
from amongus.agent import *
from amongus.game import *
from amongus.model import *
from amongus.world import *

# External Packages
import numpy as np
import torch

In [18]:
map_size = 11
num_tasks = 5
num_agents = 30
max_steps = 200

game = Game(map_size, num_tasks, num_agents, max_steps)

In [19]:
print(game.world.map)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [20]:
print(game)

--------------------------------------------------------------------
|     |     |     |  G  |     | A21 |     |     |     |     |     |
--------------------------------------------------------------------
|     | A28 |     | A20 | A14 | A16 |     |     |     |     | A18 |
--------------------------------------------------------------------
|     |     | A4  | A10 | A26 | A22 |     |     |     | A3  |     |
--------------------------------------------------------------------
| A12 |     |     |     |     |     | A29 |     | A23 |     |     |
--------------------------------------------------------------------
|  G  |     | A24 |     | A7  | A2  |     |     |     |     | A9  |
--------------------------------------------------------------------
|     |     |     | A5  |     |     | A6  |  G  |     |     | A0  |
--------------------------------------------------------------------
|     |     |     |     |     |     |     |     |     | A8  | A1  |
-----------------------------------------

In [22]:
game.agents[21].get_observation()

(array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[  0.,   0.,   0.,   0.,   0., 121.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0., 120., 114., 116.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0., 110., 126., 122.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0

In [6]:
a = game.world.map.reshape(-1)