In [13]:
# Import Project
import sys
sys.path.append('.')
from amongus.agent import *
from amongus.game import *
from amongus.model import *
from amongus.world import *

# External Packages
import numpy as np
import torch

In [14]:
map_size = 11
num_tasks = 5
num_agents = 5
max_steps = 200

game = Game(map_size, num_tasks, num_agents, max_steps)

In [15]:
print(game.world)

[[  0.   0.   0.   0.   1.   0.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   1.   0.   0.   0.   1.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 104.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 100.   0.   0.   0.   0.]
 [  0.   0.   0. 102.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 103.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 101.   0.   0.   0.   0.   0.   1.   0.   0.   0.]]


In [16]:
print(game)

--------------------------------------------------------------------
|     |     |     |     |  G  |     |     |     |     |  G  |     |
--------------------------------------------------------------------
|     |     |     |     |     |     |     |     |     |     |     |
--------------------------------------------------------------------
|     |     |     |     |     |     |  G  |     |     |     |  G  |
--------------------------------------------------------------------
|     |     |     |     |     |     |     |     |     |     |     |
--------------------------------------------------------------------
|     |     |     |     |     |     |     |     |     |     |     |
--------------------------------------------------------------------
|     |     |     |     |     |     |     |     |     |     |     |
--------------------------------------------------------------------
|     |     |     |     |     |     |     |     | A4  |     |     |
-----------------------------------------

In [17]:
game.agents

[ID: 0, Role: Impostor, Location: (7, 6),
 ID: 1, Role: Crewmate, Location: (10, 1),
 ID: 2, Role: Crewmate, Location: (8, 3),
 ID: 3, Role: Crewmate, Location: (9, 1),
 ID: 4, Role: Crewmate, Location: (6, 8)]