In [1]:
# Import Project
import sys
sys.path.append('.')
from amongus.agent import *
from amongus.game import *
from amongus.model import *
from amongus.world import *

# External Packages
import numpy as np
import torch

In [2]:
map_size = 11
num_tasks = 5
num_agents = 20
max_steps = 200

game = Game(map_size, num_tasks, num_agents, max_steps)

In [3]:
print(game.world)

[[104.   0.   0. 100.   0.   0.   0.   1.   0.   0. 108.]
 [111.   0.   0.   0.   0.   0. 102.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 109. 113.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 117.]
 [114.   0.   1.   0.   0.   0.   0.   0.   0.   0.   0.]
 [112.   0. 116.   0. 119.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   1.   0.   0. 110.]
 [  0.   1.   0.   0.   0. 115.   0. 105.   0.   0. 118.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   1.   0.   0.]
 [  0.   0. 101.   0. 107.   0. 106.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 103.   0.   0.]]


In [4]:
print(game)

--------------------------------------------------------------------
| A4  |     |     | A0  |     |     |     |  G  |     |     | A8  |
--------------------------------------------------------------------
| A11 |     |     |     |     |     | A2  |     |     |     |     |
--------------------------------------------------------------------
|     |     |     |     |     |     |     |     | A9  | A13 |     |
--------------------------------------------------------------------
|     |     |     |     |     |     |     |     |     |     | A17 |
--------------------------------------------------------------------
| A14 |     |  G  |     |     |     |     |     |     |     |     |
--------------------------------------------------------------------
| A12 |     | A16 |     | A19 |     |     |     |     |     |     |
--------------------------------------------------------------------
|     |     |     |     |     |     |     |  G  |     |     | A10 |
-----------------------------------------

In [5]:
game.agents[4].get_observation()

(array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[104.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.,   0., 108.],
        [111.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 113.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0

In [6]:
a = game.world.map.reshape(-1)